//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdSecurityEntities : DbContext
    {
        public bdSecurityEntities()
            : base("name=bdSecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbAplicaciones> tbAplicaciones { get; set; }
        public DbSet<tbAplicacionesProyecto> tbAplicacionesProyecto { get; set; }
        public DbSet<tbAplicacionesUsuario> tbAplicacionesUsuario { get; set; }
        public DbSet<tbAreas> tbAreas { get; set; }
        public DbSet<tbEstados> tbEstados { get; set; }
        public DbSet<tbPerfiles> tbPerfiles { get; set; }
        public DbSet<tbPerfilesUsuario> tbPerfilesUsuario { get; set; }
        public DbSet<tbUsuarios> tbUsuarios { get; set; }
    }
}
