//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class scConsultaMasiva
    {
        public scConsultaMasiva()
        {
            this.scConsultaMasiva_Detalle = new HashSet<scConsultaMasiva_Detalle>();
        }
    
        public int idconsulta { get; set; }
        public int idusuario { get; set; }
        public System.DateTime fechaInicia { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string rutafile { get; set; }
        public string estado { get; set; }
        public string mensaje { get; set; }
        public string rutaOrigen { get; set; }
        public Nullable<int> idUsuarioEnvio { get; set; }
    
        public virtual ICollection<scConsultaMasiva_Detalle> scConsultaMasiva_Detalle { get; set; }
    }
}
