//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAmbientesAplicacion
    {
        public int CodAmbiente { get; set; }
        public int CodAplicacion { get; set; }
        public string NomAmbiente { get; set; }
        public string Proveedor { get; set; }
        public string FuenteDatos { get; set; }
        public string NomBaseDatos { get; set; }
        public string Login { get; set; }
    }
}
