//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAplicacionesUsuario
    {
        public int CodUsuario { get; set; }
        public int CodAplicacion { get; set; }
        public string Login { get; set; }
        public string keyCheck { get; set; }
    
        public virtual tbAplicaciones tbAplicaciones { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
