//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAuditorias
    {
        public tbAuditorias()
        {
            this.tbDetallesAuditoria = new HashSet<tbDetallesAuditoria>();
        }
    
        public int CodAuditoria { get; set; }
        public Nullable<int> CodUsuario { get; set; }
        public Nullable<int> CodAplicacion { get; set; }
        public Nullable<int> CodPerfil { get; set; }
        public string Login { get; set; }
        public string EstacionUsuario { get; set; }
        public System.DateTime FechaHoraInicio { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<tbDetallesAuditoria> tbDetallesAuditoria { get; set; }
    }
}
