//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCargos
    {
        public int CodCargo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CodArea { get; set; }
    
        public virtual tbAreas tbAreas { get; set; }
    }
}
