//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompanias
    {
        public int CodCompania { get; set; }
        public string RazonSocial { get; set; }
        public string NumDocumento { get; set; }
        public int CodTipoDocumento { get; set; }
        public int CodTipoCompania { get; set; }
        public string NomRepresentante { get; set; }
        public string ApeRepresentante { get; set; }
        public string NumDocRepresentante { get; set; }
        public Nullable<short> CodTipoDocRepresentante { get; set; }
        public Nullable<System.DateTime> FechaVinculacion { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<short> Score { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaUltModificacion { get; set; }
        public string UsuarioUltModificacion { get; set; }
    }
}
