//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetallesAuditoria
    {
        public int CodAuditoria { get; set; }
        public int CodDetAuditoria { get; set; }
        public System.DateTime FechaHoraAccion { get; set; }
        public int CodOperacion { get; set; }
        public string DescripcionSQL { get; set; }
        public Nullable<int> CantRegistrosAfectados { get; set; }
        public string ObjetoEfecto { get; set; }
        public string ObjetoCausa { get; set; }
    
        public virtual tbAuditorias tbAuditorias { get; set; }
    }
}
