//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDominioUnix
    {
        public string IdMaquina { get; set; }
        public string Login { get; set; }
        public string FullName { get; set; }
        public string GroupName { get; set; }
        public string password { get; set; }
        public string userid { get; set; }
        public string prmygroup { get; set; }
        public string home { get; set; }
        public string shell { get; set; }
    }
}
