//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDominioWindows
    {
        public string Login { get; set; }
        public string FullName { get; set; }
        public string GroupName { get; set; }
        public string Comment { get; set; }
        public string AccountType { get; set; }
        public string HomeDrive { get; set; }
        public string HomeDir { get; set; }
        public string Profile { get; set; }
        public string LogonScript { get; set; }
        public string Workstations { get; set; }
        public string PswdCanBeChanged { get; set; }
        public string PswdLastSetTime { get; set; }
        public string PswdRequired { get; set; }
        public string PswdExpires { get; set; }
        public string PswdExpiresTime { get; set; }
        public string AcctDisabled { get; set; }
        public string AcctLockedOut { get; set; }
        public string AcctExpiresTime { get; set; }
        public string LastLogonTime { get; set; }
        public string LastLogonServer { get; set; }
        public string LogonHours { get; set; }
        public string Sid { get; set; }
        public string RasDialin { get; set; }
        public string RasCallback { get; set; }
        public string RasCallbackNumber { get; set; }
    }
}
