//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLogAcceso
    {
        public long idlog { get; set; }
        public Nullable<int> codusuario { get; set; }
        public Nullable<System.DateTime> fecregistro { get; set; }
        public Nullable<int> codaplicacion { get; set; }
        public string tipolog { get; set; }
    }
}
