//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOpcionesPerfil
    {
        public int CodPerfil { get; set; }
        public int CodOpcion { get; set; }
        public Nullable<bool> PermisoCreacion { get; set; }
        public Nullable<bool> PermisoConsulta { get; set; }
        public Nullable<bool> PermisoActualizacion { get; set; }
        public Nullable<bool> PermisoBorrado { get; set; }
    
        public virtual tbOpciones tbOpciones { get; set; }
        public virtual tbPerfiles tbPerfiles { get; set; }
    }
}
