//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProyectos
    {
        public tbProyectos()
        {
            this.tbDocumentos = new HashSet<tbDocumentos>();
            this.tbAplicaciones = new HashSet<tbAplicaciones>();
        }
    
        public string CodProyecto { get; set; }
        public string Nombre { get; set; }
        public string NombreInt { get; set; }
        public string UbicacionDe { get; set; }
        public string UbicacionPro { get; set; }
    
        public virtual ICollection<tbDocumentos> tbDocumentos { get; set; }
        public virtual ICollection<tbAplicaciones> tbAplicaciones { get; set; }
    }
}
