//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSiteMap
    {
        public int CodSiteMap { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> CodOpcion { get; set; }
        public Nullable<int> CodAplicacion { get; set; }
    
        public virtual tbOpciones tbOpciones { get; set; }
    }
}
