//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            this.tbAplicacionesUsuario = new HashSet<tbAplicacionesUsuario>();
        }
    
        public int CodUsuario { get; set; }
        public string Cedula { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string TelCasa { get; set; }
        public string DirCasa { get; set; }
        public Nullable<int> GrupoSanguineo { get; set; }
        public int CodCargo { get; set; }
        public int CodArea { get; set; }
        public Nullable<int> Extension { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int CodTipoContrato { get; set; }
        public string EMail { get; set; }
        public string Celular { get; set; }
        public string CodEstado { get; set; }
        public string userNT { get; set; }
        public bool IsLockedOut { get; set; }
        public Nullable<System.DateTime> LastLockedOutDate { get; set; }
        public Nullable<int> FailedPasswordAttemptCount { get; set; }
        public Nullable<System.DateTime> FailedPasswordAttemptWindowStart { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public Nullable<int> FailedPasswordAnswerAttemptCount { get; set; }
        public Nullable<System.DateTime> FailedPasswordAnswerAttemptWindowStart { get; set; }
        public Nullable<int> CodCompania { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> idUsuarioIBS { get; set; }
    
        public virtual ICollection<tbAplicacionesUsuario> tbAplicacionesUsuario { get; set; }
    }
}
